### ISSUE TITLE
autosizing weirdness when textarea is rotated

### ISSUE THREAD

**Issue by erf** [jackmoore/autosize#101]
ok - this might be far fetched but id like to have a textarea a bit tilted (rotated) using css -webkit-transform: rotate(5deg); but when typing the a line shift is happening in the middle of the line. is there a feasible solution to this do you think?

Thanks, 
Erlend

**Comment by jackmoore** [comment]
Sorry, I never took the time to investigate this.  May not be applicable any more, so I'm going to close.
