### ISSUE TITLE
allow only 1 row with append "\n" only after focus

### ISSUE THREAD

**Issue by coudrak** [jackmoore/autosize#106]
It's not a bug but I wanted to publish to help maybe other websites in the same wish.

Currently it's not possible to have a textarea with only 1 line, like the Facebook box, before you focus it, when you want append a "\n". Before it adds the \n when it initialize the textareas. When we create an area with for example a "height: 22px" (just 1 row), autosize plugin should not modify the height until you focus it.
So I added "if ($(this).is(":focus"))" for my site in the autosize script:

if ($(this).is(":focus"))
     mirror.value = ta.value + options.append;
else
     mirror.value = ta.value;

**Comment by marckohlbrugge** [comment]
:+1: Would be great to have as an option!
