### ISSUE TITLE
Textarea's not heighting properly in Firefox (on Windows, atleast)

### ISSUE THREAD

**Issue by sharikul** [jackmoore/autosize#111]
Hi, 

In the web app that I'm creating, I'm using autosize.js to automatically resize the textarea's provided. Problem is that while on Chrome textarea's are resized properly based on the amount on content, on Firefox, the last line of content in textarea's are cut off, and since the script removes the scrolls, there's no way to view the cut off content without inspecting the textarea and unchecking the `overflow: hidden` declaration. See the image below for better understanding:

![](http://cl.ly/image/1q3I0q1t3M1f/Capture.PNG)

**Comment by jackmoore** [comment]
This would probably be resolved as of 2.0.
