### ISSUE TITLE
Improper sizing while printing, content cut off.

### ISSUE THREAD

**Issue by phazei** [jackmoore/autosize#131]
If the box happens to be high enough, it seems to work.  But supposing the page is really wide on screen, so the box isn't very high, then you go to print, the height is maintained, but the width get narrower, so it gets cut off.  Not sure about a fix...

I see this behavior exhibited in print previews for latest Chrome and FF.  Other browsers unknown.

**Comment by Ciantic** [comment]
@jackmoore this does not work, it just clips and shows the scrollbars on Google Chrome print preview.
