### ISSUE TITLE
Autosize for textareas with placeholder text is setting an initial height which is too large

### ISSUE THREAD

**Issue by shedd** [jackmoore/autosize#140]
I see that Autosize was recently extended to support sizing text areas based on the placeholder text.

I'm using Bootstrap 3 and I'm seeing text areas sized much too large upon load.  Once you start typing, everything works fine and the text areas snap down to the correct size.  It's not the row/col definitions on the textareas, because the only variable that I'm changing is the placeholder text.

Example:

When the placeholder text is set to "x" for these two form fields, you see the text areas sized as I would expect and as the CSS dictates:

![screen shot 2014-02-19 at 1 26 09 pm](https://f.cloud.github.com/assets/180497/2211995/f51ee8f0-99ac-11e3-8d73-debb8aab3c65.png)

However, when you expand the placeholder text to something longer, the boxes increase substantially in size:

![screen shot 2014-02-19 at 1 26 48 pm](https://f.cloud.github.com/assets/180497/2212009/10b1b28c-99ad-11e3-998c-f4c95d1b6aee.png)

Enter anything in the boxes and then delete it, restoring the placeholder text and you're back to what I would expect:

![screen shot 2014-02-19 at 1 30 17 pm](https://f.cloud.github.com/assets/180497/2212016/21cee7ba-99ad-11e3-85ab-654c63929145.png)

Let me know if you're not able to reproduce this issue and I can provide more detail.

**Comment by krnlde** [comment]
You can set the `placeholder: false` option now.
