### ISSUE TITLE
Unnecessary extra space (boxOffset) with box-sizing: border-box on modern non-IEs

### ISSUE THREAD

**Issue by rimmer333** [jackmoore/autosize#168]
Hello.

We found that when using .autosize() against a textarea with box-sizing:border-box, unnecessary space is added in all modern non-IEs. 

All versions of MSIE calculate the height correctly and don't add any unwanted space.

That unnecessary space is equal to boxOffset.

It appears like in non-IE implementations, at least in WebKit && Gecko on HTML5 documents, the scrollTop of the textarea with box-sizing:border-box already includes the extra spacing of the element, so no need to add it back in during calculations.

**Comment by krnlde** [comment]
:+1:  This did the trick for us! Thank you.
