### ISSUE TITLE
Re-activate scrollbar in Chrome

### ISSUE THREAD

**Issue by ThibautPerninho** [jackmoore/autosize#188]
Hi,

How do I proceed to get back the scrollbar in textarea in chrome?

I noticed that in Firefox the scrollbar is always visible. I need it too be that way in chrome also as I cannot always scroll the mousewheel inside my textareas (Another scroll plugin is activated on my website: slimscroll but not in my textareas).

Thanks

**Comment by jackmoore** [comment]
Vertical scrolling is re-enabled when the css max-height of the textarea is reached.
