### ISSUE TITLE
Min-height option

### ISSUE THREAD

**Issue by apierr** [jackmoore/autosize#19]
Why don't you add a min-height option. 
Using min heigh option allows you to specify a minimum height that the object will have even if the field is empty. 

Unfortunately, setting the min-height in my CSS, autosize does not respect it.

**Comment by damianobarbati** [comment]
@jackmoore was this feature ever added? Thanks!

**Comment by jackmoore** [comment]
@damianobarbati Set a min-height and/or max-height in your CSS like you normally would.

**Comment by damianobarbati** [comment]
@jackmoore do you know if I have any chance to have this feature work with "rows"?
I can only pass (initial)rows to this text-area, I can't set min-height right now.

**Comment by jackmoore** [comment]
@damianobarbati Yeah, rows is fine too.  I'm assuming you are asking about the current version of Autosize and not the jQuery plugin (Autosize v1.x).  I can't remember what the jQuery version supported (this is a very old ticket), but I think rows worked with it as well.

**Comment by damianobarbati** [comment]
@jackmoore thanks for the feedback, unfortunately I cannot get it working.
I'm using it on a textarea https://material-ui-next.com/demos/text-fields/ inside this component, which simply generated a <textarea rows={x} />.
But if I add the `rows` to the textarea I see no height updated on the element.
I'm digging a little more into this, I'll let you know.
