### ISSUE TITLE
Max-height is parsed as pixels

### ISSUE THREAD

**Issue by STOpandthink** [jackmoore/autosize#191]
When max-height of the textarea is set as 100%, autosize interprets it a 100px.

**Comment by STOpandthink** [comment]
In firefox the value is read out as pixels, but in chrome you get %.
$("...").css("max-height")

**Comment by jackmoore** [comment]
I thought all the browsers reported it as pixels, but it looks like you are correct. Thanks for bringing it to my attention, not sure what to do about it yet.

**Comment by jackmoore** [comment]
Reworked it not to use the max-height directly, and instead infer it based on whether or not the textarea has the expected height.
