### ISSUE TITLE
IE wrong height of textarea when cloning

### ISSUE THREAD

**Issue by Knordy** [jackmoore/autosize#194]
There seem to be a bug when we are cloning a hidden textarea and add it to the page. The height of the textarea in IE11 is way to small. I've also tested in in Chrome and Firefox, but in those browsers it is working properly.

Here is a link to the jsfiddle: http://jsfiddle.net/eqme6byh/2/

What we are trying to do is: clone a hidden template, add it to the page, and show it.

**Comment by jackmoore** [comment]
The DOM can't give the correct dimensions of a hidden or detached element, which Autosize depends on in order to correctly set the height.  You should either assign autosize to the element after it has been show, or call the `autosize.resize` event after it has been shown.  For example:

```
// autosize existing textarea's
$('textarea').autosize();

// clone the template
var $elems = $('#template').clone();
// add it to the page
$('#placeholder').prepend($elems);

// also autosize the new cloned textarea
$elems.find('textarea').autosize();

// show the clone
$elems.show();

$elems.find('textarea').trigger('autosize.resize');
```
