### ISSUE TITLE
Parent element not resized.

### ISSUE THREAD

**Issue by JacquesMarais** [jackmoore/autosize#195]
I have a textarea inside a DIV. The DIV is not resizing but the textarea is, making the textarea larger than the div. Can you please help me to fix this?

**Comment by jackmoore** [comment]
Could you provide an example?  This does not sound like it's a problem with the plugin, but more likely something to do with your specific markup or stylesheet.

**Comment by JacquesMarais** [comment]
Jack Moore, I found the solution to my problem, it was that the parent element's was set to a width, not a min-width, sorry.

**Comment by jackmoore** [comment]
Great, glad you figured it out.
