### ISSUE TITLE
Max number of lines, autosize bottom-up

### ISSUE THREAD

**Issue by johnygomez** [jackmoore/autosize#196]
Hello is it possible, to restrict textarea autosize to 3 lines for example? I mean textarea will grow from 1 to 3 and after that, there will be a scrollbar visible..
My second question is, if it's possible to grow textarea in opposite direction, from bottom to top?

**Comment by jackmoore** [comment]
If you use CSS to set a max-height, then autosize will re-enable the scrollbars once that height is reached.  So for 3 lines, the max-height would be 3x your line-height.

**Comment by johnygomez** [comment]
Thanks @jackmoore, however I've also found that solution meantime. :)
