### ISSUE TITLE
Doesn't work with jquery trigger

### ISSUE THREAD

**Issue by samedii** [jackmoore/autosize#201]
So I am forced to use all this code?

var evt = document.createEvent('Event');
evt.initEvent('autosize.update', true, false);
element[0].dispatchEvent(evt);

When updating? Is this intended?

**Comment by samedii** [comment]
Maybe creating the autosize could return something that you can call update/destroy on?

**Comment by jackmoore** [comment]
Yeah, I wish you could trigger DOM native custom events from jQuery, but it seems to just understand it's own custom events.  The new method for creating a custom event isn't as verbose, but it's not supported in IE yet. 

Example using [CustomEvent](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent), which is currently available in non-IE browsers:
```
element.dispatchEvent(new CustomEvent('autosize.update'));
```

I'll get back to you on this.

**Comment by jackmoore** [comment]
My apologies for the late resolution on this.  As an alternative to using the life-cycle events, I added methods for adding and deleting.  For example:

```
var ta = document.querySelector('textarea');

autosize(ta);
ta.value = 'Some new value';
// resize the textarea
autosize.update(ta);

// remove autosize from the textarea
autosize.destroy(ta);
```

You can also now listen to the custom events using jQuery.  I had to rename the events so that they did not overlap with jQuery's custom namespace:

```
$('textarea').each(function(){
  autosize(this);
}).on('autosize:resized', function(){
  console.log('resized textarea');
});
```

**Comment by SleepWalker** [comment]
thanks for the feature :+1:
