### ISSUE TITLE
Support for Textarea with one row

### ISSUE THREAD

**Issue by Joeao** [jackmoore/autosize#202]
Hi Jack,

So my previous issue on the old repo was probably poorly written/didn't get to the point, so here goes attempt #2:

A textarea with a height set as the equivalent of one row will be Autosized to a minimum of two rows, as this is browser default when applying height:auto.

By temporarily setting the textarea to 1 row, you get the true size of content of the textarea without any interference of browser default attributes.

In your last post you mentioned that you'd rather leave it to the user to set the height of the textarea manually, which makes sense. But the user is already doing that and it's being overwritten, and setting the 'row' property as 1 permanently doesn't make sense as the textarea is meant to resize based on its content.

Example scenario:
If you're recreating Facebook chat, which is one row at first and has their own autosize functionality. By applying Autosize.js to that textarea, it will default to 2 rows as a minimum.

Example solution (With enhanced visual assistance):
![image](https://cloud.githubusercontent.com/assets/2255423/6411076/08b3472e-be75-11e4-9540-0d1a4c838c02.png)

Left: Autosize in its current state
Right: Autosize with temporary 'fix'
As you can see from the example, I'm wanting any textarea in the list have its height set to the content, with the minimum row being one, rather than two.

The right example has the following code in the Adjust function:
```javascript
function adjust() {
	var startHeight = ta.style.height;
	var rows = ta.getAttribute('rows'); // Gets current rows, if any
	var htmlTop = document.documentElement.scrollTop;
	var bodyTop = document.body.scrollTop;
	ta.setAttribute('rows', 1); // Temporarily sets rows to 1, to active True Height Technology™

	ta.style.height = 'auto';

	var endHeight = ta.scrollHeight+heightOffset;

	if (maxHeight !== false && maxHeight < endHeight) {
		endHeight = maxHeight;
		if (ta.style.overflowY !== 'scroll') {
			ta.style.overflowY = 'scroll';
		}
	} else if (ta.style.overflowY !== 'hidden') {
		ta.style.overflowY = 'hidden';
	}

	ta.style.height = endHeight+'px';

	// Sets rows back to their previous property, if it existed, else removes
	if(rows == null) {
		ta.removeAttribute('rows')
	} else {
		ta.setAttribute('rows', rows);
	}

	// prevents scroll-position jumping
	document.documentElement.scrollTop = htmlTop;
	document.body.scrollTop = bodyTop;

	if (startHeight !== ta.style.height) {
		var evt = document.createEvent('Event');
		evt.initEvent('autosize.resized', true, false);
		ta.dispatchEvent(evt);
	}
}
```

There's probably a more elegant way of carrying this out, but I would say that it's responsibility of the plugin to make sure that a textarea maintains properties that the user sets.

**Comment by jackmoore** [comment]
> But the user is already doing that and it's being overwritten, and setting the 'row' property as 1 permanently doesn't make sense as the textarea is meant to resize based on its content.

I think I would like to approach it as rows being another way of specifying the minimum height.  Not specifying a rows attribute is the same as adding `rows='2'`, as that's the default value.  So the textarea already has a value for rows regardless.  If someone wants the minimum textarea height to be a single row, then I don't mind them having to change the attribute value to be `rows='1'`.

If someone wanted the starting height to be 2 rows, then I wouldn't want autosize to change that to a single row.  I'd rather the action be explicit, rather than have the script make an assumption.

**Comment by Joeao** [comment]
Hi Jack,

Yeah that makes sense actually. I seem to have made some wrong assumptions about how this should work; By doing it my way you'd actually be enforcing something that is against the norm, which would result in unexpected behaviour.

In that case, anyone reading this in the future:
As Jack said, set rows on the textarea to 1 and it will still be autosized with a minimum of one row rather than two.

Thanks for the plugin, guy.
