### ISSUE TITLE
Scrolling the page on Mobile Safari causes the page to jump when using autosize

### ISSUE THREAD

**Issue by jeffijoe** [jackmoore/autosize#207]
Try scrolling http://www.jacklmoore.com/autosize/ up and down with an iPhone - when the URL bar is resized, the page will freeze/jump.

Any quickfix?

**Comment by joaocunha** [comment]
Related to #239.

**Comment by rmcauley** [comment]
In case somebody else is searching issues for this; this can also be described as autosize stopping kinetic scrolling / inertia scrolling / inertial scrolling from working on iOS.

An easy temporary fix is disabling autosize from acting on screen resize, which could affect mobile users when switching from landscape to desktop.  Perhaps a workaround for this could be to add code to check if the screen width has changed - if only vertical size has changed then don't act.

**Comment by riomyers** [comment]
You can fix this with the following css on the html `height:100%;min-height:100vh;margin-bottom:-20px;transition: min-height 999999s;`
