### ISSUE TITLE
How to unbind

### ISSUE THREAD

**Issue by cseufert** [jackmoore/autosize#210]
I have a large Single page app, and I need to unbind the event handlers when dialog/pages are closed, I cant find any api to do this.

**Comment by jackmoore** [comment]
Are you using the current version, or the jQuery plugin (1.x)?  Either way you would trigger the `autosize.destroy` event.  For the current version, this is documented on the [project page](http://www.jacklmoore.com/autosize/).  For the jQuery version, you would call the following:
```
$('textarea').trigger('autosize.destroy');
```

**Comment by jackmoore** [comment]
For the jQuery plugin (1.x), use the destroy event:
```
$('textarea').trigger('autosize.destroy');
```

For autosize 3.x, use the following destroy event:
```
var ta = document.querySelector('textarea');
var evt = document.createEvent('Event');
evt.initEvent('autosize:destroy', true, false);
ta.dispatchEvent(evt);
```

Alternatively, in 3.x you can use the new destroy method:
```
var ta = document.querySelector('textarea');
autosize.destroy(ta);
```
