### ISSUE TITLE
PhantomJS Error

### ISSUE THREAD

**Issue by andyburton** [jackmoore/autosize#211]
When using this with PhantomJS i get the following error which i can't seem to resolve:

TypeError: 'undefined' is not a function (near '...-autosize-on")}.bind(ta,{height:ta.style...') - https://github.com/jackmoore/autosize/blob/master/src/autosize.js#L110

JS code is very simple:

$(function () {
    autosize($('.cfs textarea'));
});

I've also tried sticking that into a loop to set each element individually and still get the same error for each element.

**Comment by jackmoore** [comment]
Apparently PhantomJS has only supported `Function.prototype.bind()` since version 2.0 ([ticket](https://github.com/ariya/phantomjs/issues/10522)).  So if you can upgrade to PhantomJS 2.0, that should resolve the issue.  Otherwise, you would have to polyfill bind.
