### ISSUE TITLE
Rows set but with height auto

### ISSUE THREAD

**Issue by amnesia7** [jackmoore/autosize#212]
Bootstrap sets textareas to have height: auto.

I'd like to just set rows="8" on my textarea and it to be respected. In firefox and chrome it seems to be but in IE10 it contracts the textarea to be a single line high, ignoring the number of rows. 

Can autosize take the rows number into account for the start height if no height/min-height is set?

I've currently set min-height to be 8 x line-height but this isn't quite as accurate of a height for the textarea as rows would be, I assume because it is taking the padding (and possibly border) into account as well so I end up with a textarea that's about 7 and a half lines high (but does still expand).

**Comment by jackmoore** [comment]
Using rows seems to work for me in IE9-11.  Can you provide a link demonstrating the problem?

**Comment by jackmoore** [comment]
Here is a demo I put together, which works fine for me in IE: http://jsfiddle.net/zxs8utb9/

**Comment by amnesia7** [comment]
@jackmoore try this (http://jsfiddle.net/hrnm9fg4/1/) in either IE9 or IE10 (I haven't got an IE11 to check it with). I'm using a modernIE Win7 IE10 VM to check it (changing between them using the dev tools).

**Comment by jackmoore** [comment]
> I'm using a modernIE Win7 IE10 VM to check it

Sorry for the late reply, but I haven't been able to reproduce the issue.  I also installed the Win7 IE10 VM to test this, and it all worked fine for me (showed the correct number of rows).
