### ISSUE TITLE
Module not found when getting autosize from node_modules using browserify

### ISSUE THREAD

**Issue by PacciniBruno** [jackmoore/autosize#215]
adding ```"main": "dest/autosize.js"``` to autosize package.json config solves the problem.

Would a pull request be relevant here ? (first time I report an issue on an open source project :smile: I'm still learning the rules)

**Comment by PacciniBruno** [comment]
My bad ... someone already raised that isse and created a pull request. https://github.com/jackmoore/autosize/pull/214
I'm not finding any ```"main"``` property in package.json when installing autosize from npm though :crying_cat_face: so I guess the issue remains ?

**Comment by jackmoore** [comment]
Thanks.  I had to do a version bump and publish to NPM again so that the package change was included in the tagged version. Oversight on my part, sorry about that. Resolved now with version 2.0.1.

**Comment by PacciniBruno** [comment]
Amazing! Thanks a lot
