### ISSUE TITLE
Substitute of  'autosize.resize' in new version 

### ISSUE THREAD

**Issue by ellhn** [jackmoore/autosize#221]
I used to use method 'autosize.resize' in the old version v1 as to adjust the textarea height to its content  in case it was fed with data directly from database and not by typing/pasting data into it,
 e.g. $("#comments").val(data).trigger('autosize.resize'); 
did excellent my job for a textarea with id="comments" and data getting with json from server.

However, I cannot achieve to do the same with the new version I've downloaded (3.0.2). 
What exactly do I have to write as to get the above behavior?

Thank you very much

**Comment by jackmoore** [comment]
Using your example, you could do the following:
```
autosize.update($('#comments').val(data));
```

Or you could trigger the event yourself:
```
$('#comments').val(data).each(function(){
  var evt = document.createEvent('Event');
  evt.initEvent('autosize:update', true, false);
  this.dispatchEvent(evt);
});
```
