### ISSUE TITLE
SyntaxError: missing ; before statement

### ISSUE THREAD

**Issue by khashabawy** [jackmoore/autosize#222]
SyntaxError: missing ; before statement
	

let endHeight = ta.scrollHeight+heightOffset;

**Comment by jackmoore** [comment]
Sorry, that's not enough information for me to be able to reproduce the problem.  The code looks fine to me.  I'm guessing you should be using the file in the dest folder, and not the source file which needs to be transpiled.

**Comment by seismicsix** [comment]
Hi,
Make sure you're using the autosize.js from the dest folder, not the src folder.
Hope this helps!
