### ISSUE TITLE
Require.js autosize v2 Script error

### ISSUE THREAD

**Issue by trompx** [jackmoore/autosize#223]
Hello,

First thanks for the great plugin. Up until now I was using autosize v1 with require js. I had in my config file the following :
paths: {
  'jquery.autosize': 'libs/jquery.autosize'
},
shim: {
  'jquery.autosize': { exports: 'autosize', deps: ['jquery'] }
}

I tried to import the new v2 version but I can't make this works:
paths: {
  'autosize': 'libs/autosize'
}
but I get an "Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode : line 50" error message.

Do you know what is the correct config to load the v2 autosize with require.js ?

Thank you

**Comment by trompx** [comment]
Replaceing line 50 :
let endHeight = ta.scrollHeight+heightOffset;
with :
var endHeight = ta.scrollHeight+heightOffset;
solves this issue.

But then I get the following error :
"Uncaught SyntaxError: Unexpected token =>" on line 86 "const destroy = style => {"

**Comment by jackmoore** [comment]
I can't tell what you are doing, but you should be using the files in the dest directory.

**Comment by trompx** [comment]
Yes my bad I was using file in src folder^^ So there was problem with require js and ES6 ... so I converted back to ES5 to make it work, but yeah I will use files of dest folder. Thank you again.
