### ISSUE TITLE
Callbacks

### ISSUE THREAD

**Issue by SimonSteinberger** [jackmoore/autosize#228]
Hi Jack,

love your rewrite into vanilla JS! Just a thought: Personally, I think callbacks are extremely useful for such plugins, e.g. the original callback on resize of Autosize version 1.x. Right now, we can bind handlers to the custom events, which works fine technically. However, it involves more code and is more complicated than simply passing a callback function to the plugin options.

Is there a reason for your design choice? I'm also asking because I'm publishing vanilla JS plugins on my own and so far I was using callbacks instead of custom events ...

**Comment by jackmoore** [comment]
No strong reason.  I knew I wanted to provide an event as they are a little more useful: can be added or removed at any time, or delegated further up the DOM tree.

I was hoping at the time this version would be narrow enough in scope that it wouldn't need additional parameters for options (such as a callback), but I've already missed that goal. At the time I didn't feel like there needed to be two ways to do it, but reflecting I feel like adding a callback would probably be the best thing to do.

If you are only assigning to a single textarea, then event vs callback is a similar amount of code, but if you are working with a nodeList using a callback would be much less code. One thing that jQuery really nailed was that it used the same API for working with one or many elements.

**Comment by SimonSteinberger** [comment]
Thanks for the great explanation.

I think it would be really great to have some guidelines on how a vanilla JS plugin should be designed - concerning callbacks, events, options, and particularly selectors (single node, nodelist, CSS selector, or even jQuery objects). In jQuery it's mostly a clear thing.
