### ISSUE TITLE
Flicker on IE 10 and 11

### ISSUE THREAD

**Issue by SimonSteinberger** [jackmoore/autosize#229]
Autosized textareas show a slight flicker on resize in IE 10 and 11. I fear without an invisible clone element (as in version 1), this will be hard to avoid ... Astonishingly, IE 9 doesn't have this problem.

**Comment by jackmoore** [comment]
I have the same concerns.  I tested this before publishing the rewrite, and didn't notice any flicking, but I used a VM for testing IE.  The slower performance of using windows in a VM might have masked the flickering.

**Comment by SimonSteinberger** [comment]
Stupid IE - as always :-D

**Comment by andreyvolokitin** [comment]
So there is nothing can be done about it?

**Comment by jackmoore** [comment]
I guess not, but I'm open to contributions here.  I think the only thing that could be done would be move back to use a mirrored textarea element, but I don't have any intention on doing that because it opens the door to a different set of problems.
