### ISSUE TITLE
Feature request - additional lines/buffer

### ISSUE THREAD

**Issue by cpinfold** [jackmoore/autosize#232]
It would be useful to have the option to add additional lines to the initial sizing to allow for additional input before a resize is triggered.  Unless there is another way to do this when autosize is calculating the initial size?  Thanks.

**Comment by jackmoore** [comment]
You can use the rows attribute on the textarea element, or set a minimum-height in your CSS.

**Comment by cpinfold** [comment]
Both good options if I knew how many rows of text I had based on wrapping and then calculated the height or wanted a fixed height.  This would duplicate the height calculation in autosize though.

I'm hoping for a height as calculated by autosize + ? rows option.

**Comment by jackmoore** [comment]
I understand.  I have a pretty narrow scope for this script and I am not currently interested in adding something like that.
