### ISSUE TITLE
Autosize is not updated when angular JS change the value

### ISSUE THREAD

**Issue by MrGrabazu** [jackmoore/autosize#233]
I'm using autosize on textarea managed by angularJs and when my model change the value of textarea are changed but autosize don't resize the textarea. 
Do you know why ? And do you know a solution to get it work ?

Thanks,
Kevin.

**Comment by jackmoore** [comment]
Does Angular give you some sort of callback or event to know when this has happened?  If so you would call autosize's `update` method, or trigger the `autosize:update` event after Angular has changed the textarea value.  Autosize uses the change event to detect user interactions, but there is no way to observe when the textarea value has changed through setting the value property.

**Comment by MrGrabazu** [comment]
I just found the solution after I post this ticket !! And like you said I
use the update method.
So thank you for your answer :)

Kevin
