### ISSUE TITLE
autosize.update does not work if element is hidden

### ISSUE THREAD

**Issue by ellhn** [jackmoore/autosize#234]
I am using the new v2 version (actually, autosize.js at its top refers to 3.0.2 version!) and autosize.update does not change the height of the textarea as to accomodate all its data if textarea element is hidden at the time the above command (autosize.update) is executed. In case textarea is previously displayed, no problem occurs. However, my page structure requires the first approach.
Is there any kind of solution for that? For the time being, I can see only part of textarea data since textarea height is not flexible.
Thank you very much

**Comment by jackmoore** [comment]
See this: http://www.jacklmoore.com/autosize/#faq-hidden

**Comment by dfcreative** [comment]
@jackmoore I use autosize@3.0.8 and the described `autosize.update`:
```html
<body></body>
<script type="text/javascript" src="node_modules/autosize/dist/autosize.js"></script>
<script type="text/javascript">
	var ta = document.createElement('textarea');

	autosize(ta);
	document.body.appendChild(ta);

	autosize.update(ta);
</script>
```
and this simple code just doesn’t work.

**Comment by jackmoore** [comment]
Thanks @dfcreative, that is helpful.  I can confirm that is a bug.

**Comment by intellisense** [comment]
:+1: Confirmed this is a bug, is there a simple fix for this?

**Comment by radenkozec** [comment]
@jackmoore I tried to call autosize.update without success. Is there a fix for this?

**Comment by jackmoore** [comment]
@radenkozec Was the textarea still hidden?  The textarea needs to have layout in order for Autosize to be able to determine the size.  If the textarea had layout then I'd need to see a demo in order to resolve your issue.

**Comment by knguyen93** [comment]
I have called the autosize.update(ele), but it seem like this func was trigger before the html DOM is visible (when some model.isEditing is set to true)
