### ISSUE TITLE
Only lets me type in zero or one letter

### ISSUE THREAD

**Issue by goddamnyouryan** [jackmoore/autosize#236]
Sometimes, seemingly randomly, when I set autoresize on my textarea it only lets me enter 0 or 1 letter. It might actually be letting me add more letters but I can't see them. And If I do a `$('textarea').val() it only returns 2 letters (even though i can only see one) even if i have typed 50 letters into the textarea.

I tried removing all the css attached to my textarea in my app but no dice.

Even weirder, in the chrome inspector, if I edit or remove one of the css styles after the page as loaded it starts working perfectly (usually) but never right off the bat. It doesn't seem to matter which css style i change.

Finally, my app is a single page JS app, so I'm making sure not to call `autoresize` until after the textarea is in the DOM.

Here is my textarea:

`<textarea autofocus="true" name="body" placeholder="Message"></textarea>`

**Comment by jackmoore** [comment]
Sorry, this isn't something I've experienced or had any other reports about, so without precise way to reproduce the problem I am probably not going to be able to help with this.
