### ISSUE TITLE
'autosize:resized' is not triggered when 'changeOverflow' happens.

### ISSUE THREAD

**Issue by vogdb** [jackmoore/autosize#244]
Please look at the fiddle http://jsfiddle.net/0p9cx11q/2/. Open the console there, paste the dummy text below into the textarea, no event is fired.
`Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.`

The same problem will happen if we remove all the text inside textarea at once.

**Comment by jackmoore** [comment]
Good catch, and thanks for the demo.

**Comment by adam-lynch** [comment]
:+1:
