### ISSUE TITLE
Make it work for <input type="text"> too

### ISSUE THREAD

**Issue by binarykitchen** [jackmoore/autosize#247]
That would be awesome

**Comment by jackmoore** [comment]
Thanks for the suggestion, but this doesn't sound like something I would pursue.

**Comment by binarykitchen** [comment]
why not? i have a very good reason: textareas do not support: `type="email"` nor `multiple="true"`. these powerful attributes are missing for textareas.

**Comment by jackmoore** [comment]
I don't believe this would be possible.  `input` elements do not support line-wrapping and there's nothing this script would be able to do to enable that.

**Comment by binarykitchen** [comment]
hmmm, too bad. probably that's something for HTML6?

**Comment by hotmeteor** [comment]
Are you trolling?

**Comment by joaocunha** [comment]
He better be.

**Comment by binarykitchen** [comment]
not trolling here, just food for thought for the next html: if text inputs come with types and the multiple flag, why not make these work on textareas as well? browser implementation shouldn't be too hard when existing code is shared between both components.

**Comment by joaocunha** [comment]
`multiple` is supposed to flag multiple file uploading, it has nothing to do with autosize.

**Comment by binarykitchen** [comment]
throw an error in that case saying this combination isn't supported
