### ISSUE TITLE
Was this plugin developed for jQuery before, but support for jQuery has been dropped now?

### ISSUE THREAD

**Issue by bartclaeys** [jackmoore/autosize#249]
I wanted to upgrade this plugin, but noticed that it no longer supports jQuery. Is this correct?

**Comment by bartclaeys** [comment]
Ok, my mistake, I had to change `$('.jobappreplyfield').autosize();` into `autosize($('.jobappreplyfield'));`

**Comment by jackmoore** [comment]
👍
