### ISSUE TITLE
Src not up to date

### ISSUE THREAD

**Issue by robinfehr** [jackmoore/autosize#250]
Hi there just had a quick look at your script and saw:

function assign(ta, {setOverflowX = true, setOverflowY = true} = {}) {
...
=> (arrow function expressions)
...  
}

looks like you played around and uploaded an es6 compatible version of your script. 
took me some time :palm_tree: would be great if you could upload the other as well.

thank you.
robin

**Comment by joaocunha** [comment]
@robinfehr you can find the production-ready version under `/dist`. `/src` is intended to be ES6, you have to transpile it with Babel.

**Comment by jackmoore** [comment]
@robinfehr is correct.
