### ISSUE TITLE
wrong textarea height when textarea is hiden 

### ISSUE THREAD

**Issue by QiiSyhx** [jackmoore/autosize#252]
&lt;div id="tab1">
&lt;textarea>something</textarea>
&lt;/div>
&lt;div id="tab2">
&lt;textarea>something</textarea>
&lt;/div>

when page start, tab1 is show,tab2 is hide. I change to tab1 hide,tab2 show, tab2 textarea height is incorrect.

**Comment by jackmoore** [comment]
Did you read this?
http://www.jacklmoore.com/autosize/#faq-hidden

**Comment by QiiSyhx** [comment]
i was read it and fixed this problem with autosize.update(ta);
thanks.
