### ISSUE TITLE
Autosize does not seem to work on cloned element

### ISSUE THREAD

**Issue by bmozza** [jackmoore/autosize#254]
I have a situation whereby I am cloning a textarea which already has autosize attached. However, on cloning, whether I call update or destroy and then reassign, autosize does not correctly function. The initial height is reset but on creating a new line, the height is not incremented.

**Comment by jackmoore** [comment]
I didn't test this, but as a quick fix you can probably remove the 'data-autosize-on' after cloning in order to be able to reassign.  No need to call destroy unless you are also cloning events.

**Comment by jackmoore** [comment]
Assuming this new version will fix it, let me know if that doesn't work.
