### ISSUE TITLE
Need consultation about complex autosize setup with 'css flex'.

### ISSUE THREAD

**Issue by vogdb** [jackmoore/autosize#256]
Hi @jackmoore! Sorry that I couldn't resolve this issue by myself and asking you for a hint.
I have this autosize usage (I've simplified it as much as possible) http://jsfiddle.net/Lcw2s11u/1/. There I'm doing a scrolldown on every `autosize:resized` event in order to make the bottom text to be always presented before user eyes. The problem is that when the autosize mechanism works, it sets the textarea's height to `auto` for a moment and that prevents scrolling to the bottom of `.content`. It can be easily see if you paste a long text that would trigger `autosize:resized`. Right after that moment the scrolldown will be correct but as soon as you press any key the scrolldown will break.

Here is the video demonstration https://youtu.be/3-E2YR6Hr0Y. If you have any clues, I would gladly hear them. Thank you for your time.

**Comment by jackmoore** [comment]
This could be avoided if the textarea height didn't impact the height of the content.  So if it's possible for you, I would suggest moving the textarea ouside of the `.area` element:

http://jsfiddle.net/Lcw2s11u/2/

**Comment by jackmoore** [comment]
I could edit autosize so that it has another callback that runs after it takes it's calculation, but that seems really suboptimal.

**Comment by vogdb** [comment]
Oh, no need for another callback. Thanks for your help! I really appreciate it.
