### ISSUE TITLE
'Set' not defined in various browsers

### ISSUE THREAD

**Issue by stenrap** [jackmoore/autosize#257]
Release 3.0.10 [introduced](https://github.com/jackmoore/autosize/commit/08d62d08afde5c6cf54476fc2e184b6a3f97cd87#diff-900ca5a7be7c7ce8ba84e56867a5f573R21) a reference to the JavaScript `Set` object, which is part of the ES6 standard and isn't fully supported by [many browsers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set#Browser_compatibility).

This seems like a change that should not be part of a simple patch release—in fact, with this change you can no longer claim support for IE 9, Android 4, and most versions of Safari (iOS and desktop). Our product uses autosize, and we just got a flood of support tickets from users with these browsers because of this change (we had `"autosize": "^3.0.6"` in our package.json).

**Comment by jackmoore** [comment]
IE9 support was intended, broken by accident.

**Comment by timbru31** [comment]
Thanks for the quick fix! :cookie:
