### ISSUE TITLE
textarea not resized when value changed programatically

### ISSUE THREAD

**Issue by radvis** [jackmoore/autosize#259]
Good day, great work on a plugin!
i was playing around with it and noticed strange behavior: when i change value programatically the size is not updated to initial size. for instance: i enter a some text to cause textarea to resize then i empty the value from javascript, value changed to empty, but the size remains large, shouldn't it resize to original small size?
what i did, went here: [autosize](http://www.jacklmoore.com/autosize/) . Added  bunch of text,  opened developer console add executed this line document.getElementById('autosize-example').value=''

**Comment by jackmoore** [comment]
The plugin has no way of knowing that you did that, outside of continuous polling.  This is covered in the docs under the autosize:update lifecycle event: http://www.jacklmoore.com/autosize/

**Comment by andreszs** [comment]
And it does not have a way to **manually tell the plugin** about it either... I have tried all possible events including `$('textarea').keyup() / keydown() / change()` / etc and the plugin persistently **fails to recognize that content has changed** in textarea must be resized.

**Comment by jackmoore** [comment]
> manually tell the plugin

It's well documented how to manually tell the plugin that the text has changed.  These are your two options:

1) Call the update method:
```
autosize.update(document.querySelector('#your-textarea'));
```

2) Trigger the lifecycle event:
```
var evt = document.createEvent('Event');
evt.initEvent('autosize:update', true, false);
document.querySelector('#your-textarea').dispatchEvent(evt);
```
