### ISSUE TITLE
How to make textarea autosize work within an accordion panel view

### ISSUE THREAD

**Issue by ruchidalal** [jackmoore/autosize#260]
I have a jsp with accordion view. These have textareas in panels. By default the panels are collapsed.
I have applied autosize on all textareas. However, they dont size correctly with the accordion view. Textareas with larger content appear to be clipped. There is no scroller as well. How to achieve autosized textareas with the accordion view.

**Comment by jackmoore** [comment]
http://www.jacklmoore.com/autosize/#faq-hidden

You'll need to run autosize.update once the panel is back in the document flow.
