### ISSUE TITLE
V2 jumpy in IE11

### ISSUE THREAD

**Issue by ristarr11** [jackmoore/autosize#262]
Hello, 

Thank you for the version 2, it is great plugin, but I think there is still an issue for IE11 browsers.
I tried several different computers, and even demo causes text to jump when you are at last line and hit Enter.
Issue is fairly described here ( https://github.com/jackmoore/autosize/issues/148 ), and you mentioned you have fixed it, but I have downloaded latest V2 version, and still there it is.

Is there a way we can avoid jumpiness?

I found out that padding-bottom can be partial solution (like 20px), though.

Thank you again...

**Comment by robneild** [comment]
The textbox is scrolling before it's height is increased

I have tried to improve this various ways, but nothing worked

**Comment by JohnBergman** [comment]
We see it in Chrome too.
