### ISSUE TITLE
commonjs friendlier?

### ISSUE THREAD

**Issue by dynnamitt** [jackmoore/autosize#263]
Are "we" here;
http://blog.npmjs.org/post/111475741445/publishing-your-jquery-plugin-to-npm-the-quick

or here;
http://blog.npmjs.org/post/112064849860/using-jquery-plugins-with-npm

?

I ask because I cannot use
"ender build jquery jquery-autosize" without getting this error in browser;

Uncaught ReferenceError: jQuery is not definedModule.createPackage.jquery.autosize @ jquery.autosize.js:273Module._load @ commonjs.js:93require @ commonjs.js:17(anonymous function) @ snap.js:568(anonymous function) @ snap.js:568
jquery

**Comment by jackmoore** [comment]
It depends if you are using the current version or not.  The jQuery plugin version of autosize is no longer maintained and was not built for module loading.  However, the current version (`npm install autosize`) is built using the universal module definition, and should be compatible with AMD or Node/CommonJS.
