### ISSUE TITLE
Getting "Unexpected Token {" in Opera

### ISSUE THREAD

**Issue by levitating** [jackmoore/autosize#265]
Hi,

In Opera (possibly other browsers too), autosize does not work. When inspecting the console, I can see this :

Uncaught SyntaxError: Unexpected token { autosize.js:17
(index):287 Uncaught ReferenceError: autosize is not defined(anonymous function) @ (index):287

Notes : 
- autosize.js comes directly from your zip file and has not been modified.
- If for some reason you can't replicate this issue and you want to see this error live, let me know where i can message you privately and i will send you my website URL.

**Comment by jackmoore** [comment]
My guess is that you are using the file from the src directory, and not the dist directory.  The dist directory has been transpiled from the ES6 source to be run in a browser... so make sure that's what you are using.

**Comment by levitating** [comment]
Ah that was exactly it! Thank you for the quick answer. :)

I love the script by the way, I will be using it in every site I make in the foreseeable future. Thanks you for providing this resource, and keep up the great work! :)

**Comment by jackmoore** [comment]
👍

**Comment by addisu** [comment]
Hey,
I was using "jquery.autosize" using require for a while and today I replaced it with the new "autosize" plugin.

Unfortunately, I am getting the following issue and I couldn't figure it out ...

Uncaught TypeError: this.$('textarea').autosize is not a function

I replaced my initialization like ..

autosize(this.$('textarea')); and I am getting different error..

Uncaught ReferenceError: autosize is not defined

for now, I will roll back to the old jquery.autosize .. :smile:

**Comment by lykmapipo** [comment]
use window.autosize = window.autosize ? window.autosize : require('autosize');
