### ISSUE TITLE
Content cut off when printing from Chrome

### ISSUE THREAD

**Issue by lastmj** [jackmoore/autosize#267]
Sometimes when printing from Chrome, the text looks cut off in the print preview. 

Here's a minor example:
![screenshot from 2015-10-31 13 07 20](https://cloud.githubusercontent.com/assets/7000719/10865433/ba0b5774-7fd0-11e5-88bf-ed2813a87223.png)

You can see that the last line is cut off slightly in Chrome's print preview.

Here's a more major example. A significant portion of text is just missing from the print preview:
![screenshot from 2015-10-31 13 07 53](https://cloud.githubusercontent.com/assets/7000719/10865437/f9cddbca-7fd0-11e5-9178-bfc779746d09.png)

The whole text should be:

 Eos in tation adipiscing, vim legere virtute no. Ne mutat dicit aliquando duo. Cu etiam sadipscing nec, an vim tacimates pericula. An pro quando melius animal, nec etiam soleat vituperatoribus eu, feugiat vivendo usu ex. Sit ignota impetus iracundia at, eu quo omnis hendrerit, ex fugit luptatum pri. Id has idque docendi efficiantur, pri ut laudem conceptam.

Mea graecis delectus fabellas ea, id sea legere molestiae. No quo possim verear veritus, assum movet et eam, cu scaevola qualisque mea. Mei ut munere timeam conceptam, etiam moderatius signiferumque mea ea. Ei ocurreret repudiandae qui, pri in delenit fierent lucilius, vivendo dolores constituto id mel. Per ei primis salutatus consequuntur, percipit dignissim ut vix.

I'm not sure if this is just Chrome's problem, or something needs to be changed with autosize, or maybe I need to do something differently. Thanks!

**Comment by jackmoore** [comment]
My guess is that when you go to print, some styles change (different typographic styles, or maybe the textarea width changes, etc) and autosize does not recalculate the textarea dimensions to account for that.  So the text in the textarea element doesn't fit within the given inline style for the width and height.  I don't think there is anything autosize can do to account for this (there is no event to listen to for this), but it also seems like a different problem than what autosize is meant to address, so I think I'll close this ticket as it's unfixable and out-of-scope.

A normal textarea element (without autosize) would trim the text as well.  My feeling is that if you want the full text when printing, then you need to get the text outside of the textarea element.  You could use JavaScript to hook into the textarea's onchange event to mirror the textarea value in something like a `<div>` that's `display:none` on screen but visible for print, and set the textarea's style to be `display:none` on print.

**Comment by jackmoore** [comment]
Here's a short example:
```
<!DOCTYPE html>
<html>
	<head>
		<meta charset='utf-8'/>
		<style>
			.print {
				display: none;
			}

			@media print {
				.no-print {
					display: none;
				}
				.print {
					display: block;
				}
			}
		</style>
	</head>
	<body>
		<textarea class='no-print'>The coconut palm (also, cocoanut), Cocos nucifera, is a member of the family Arecaceae (palm family). It is the only accepted species in the genus Cocos.[2] The term coconut can refer to the entire coconut palm, the seed, or the fruit, which, botanically, is a drupe, not a nut. The spelling cocoanut is an archaic form of the word.[3] The term is derived from 16th-century Portuguese and Spanish coco, meaning "head" or "skull",[4] from the three small holes on the coconut shell that resemble human facial features.</textarea>
	</body>
	<script src='../dist/autosize.js'></script>
	<script>
		var els = document.querySelectorAll('textarea');

		autosize(els);

		Array.prototype.forEach.call(els, function(el){
			var div = document.createElement('div');

			div.textContent = el.value;
			div.classList.add('print');
			el.addEventListener('input', function(e){
				div.textContent = el.value;
			});
			el.parentNode.insertBefore(div, el);
		});
	</script>
</html>
```

**Comment by lastmj** [comment]
For future reference in case anyone runs into this problem, I believe the problem was that I was changing all of the text in my document from serif to sans-serif just before printing. The textareas do not automatically change their height when you change the size of the text, and serif versus sans-serif fonts take up different amounts of space. What I do now is call autosize.update with the textareas whose heights I want to update as the first argument, and it readjusts and seems to print correctly now.
