### ISSUE TITLE
working with require.js issue

### ISSUE THREAD

**Issue by addisu** [jackmoore/autosize#268]
Hey,
I was using "jquery.autosize" using require for a while and today I replaced it with the new "autosize" plugin.

Unfortunately, I am getting the following issue and I couldn't figure it out ...

Uncaught TypeError: this.$('textarea').autosize is not a function

I replaced my initialization like ..

autosize(this.$('textarea')); and I am getting different error..

Uncaught ReferenceError: autosize is not defined

for now, I will roll back to the old jquery.autosize .. :smile:

**Comment by jackmoore** [comment]
I'm afraid that's not enough information for me to go on.  It's fine to continue using the jQuery version, but the new version is certainly stable.  If you are experiencing a problem my guess would be that it is some minor issue with how it's being called or included.

**Comment by jackmoore** [comment]
I don't use require.js, but my guess is that you need to name the import.  The autosize jQuery plugin didn't need to be assigned to a variable because it added itself to an existing object (jQuery).

**Comment by jackmoore** [comment]
I think it would be something like this:
```
define(['autosize'], function (autosize) {
  autosize(this.$('textarea'));
});
```

**Comment by addisu** [comment]
true , seems working that way .. thanks !!
