### ISSUE TITLE
Prevent autosize manually?

### ISSUE THREAD

**Issue by gregblass** [jackmoore/autosize#272]
Is it possible to manually prevent autosize from triggering? 

I would do this in an if statement for certain cases (for example, I'm submitting the form on the enter key, and I don't want it to resize the box in that case...or display a modal saying 'you didn't enter anything' if the textarea is blank). Both cases I don't want autosize to fire.

**Comment by jackmoore** [comment]
Have you attempted this already?  I don't see why either of those things would cause autosize to trigger.

**Comment by gregblass** [comment]
...not following. Just press enter on an autosize. It will increase the size of the box...

**Comment by gregblass** [comment]
Maybe the confusion stems from the fact that I'm using a remote form? There is no page refresh. So the textarea remains larger due to the enter key press.

**Comment by jackmoore** [comment]
I'm going to say no, because this doesn't seem like something the script should have to account for.  Forms aren't normally submitted when pressing enter, if a textarea is receiving input.

**Comment by gregblass** [comment]
I respectfully disagree... Check out facebook on a desktop. Type a comment and press enter. The form is submitted.

**Comment by gregblass** [comment]
Regardless of our opinions on how apps should function, I'm simply asking if there is a way to "preventDefault", so to speak, in certain cases. Simple question, seems like the answer is no. If not I can take a look at the source code and see if I can figure out the easiest way to implement something like that.

**Comment by jackmoore** [comment]
That's not browser default behavior for submitting forms, it's not really a matter of opinion.  But, I see what you are getting at.  You could bind to the keydown event to prevent the default action, which should prevent textarea from receiving an input event (this is what autosize is listening to).  For example:

```
var ta = document.querySelector('#my-textarea');
var form = document.querySelector('#my-form');

ta.addEventListener('keypress', function(e){
	if (e.keyCode === 13) {
		e.preventDefault();	
		form.submit();
	}
});

autosize(ta);
```

**Comment by gregblass** [comment]
Excellent, thanks for the help. I was doing e.preventDefault, but hooking into the wrong place, so it wasn't actually preventing autosize from firing. I bet this will do the trick. Cheers!

**Comment by gregblass** [comment]
I actually had it pretty close in the first place, it was only a matter of changing 'keyup' to 'keypress'. Thanks for helping me track that down.
