### ISSUE TITLE
Height is set incorrectly when update() causes the textarea to change width

### ISSUE THREAD

**Issue by FredrikC** [jackmoore/autosize#274]
When the update() method causes a resize that forces the containing element to show a scrollbar the calculated height might not be correct and all text might not be shown.

See example: https://jsfiddle.net/tca8ogb0/

**Comment by jackmoore** [comment]
I don't see any problem with this.  Changing the height and overflow of parent elements is way outside the scope of what I would expect Autosize to handle.

**Comment by jackmoore** [comment]
The textarea height is sized to the content as expected, but the parent element you set a height for is clips it.

**Comment by FredrikC** [comment]
Please look again, the number 9 should be visible in the textarea, shouldn't it?

**Comment by jackmoore** [comment]
I don't think I'm seeing what you are send, can you send a screenshot and note what browser and version you are using?

I don't see a difference between the textareas, but I wouldn't expect one either because the only thing different between them is the ID (and the amount of characters in the textarea value).  I'm viewing in Chrome and Firefox on OSX.

**Comment by jackmoore** [comment]
This is what I see when I scroll down the parent divs:

<img width="355" alt="screen shot 2015-12-16 at 12 15 12 pm" src="https://cloud.githubusercontent.com/assets/59797/11848103/b6b7db64-a3ee-11e5-8ca8-e479ed525a95.png">

**Comment by FredrikC** [comment]
Sorry, my example only works as intended in latest Chrome and Opera. Internet Explorer Edge and latest Firefox has the opposite problem where 'Does not work' actually works but 'Does work' doesn't.

The key is that the scrollbar causes any line to word wrap, the first one in my example.

Chrome not scrolled
![Chrome not scrolled](http://i.imgur.com/hgbCgzk.png)

Chrome scrolled
![Chrome scrolled](http://i.imgur.com/K3BIBzy.png)

Opera not scrolled
![Opera not scrolled](http://i.imgur.com/KTdrArP.png)

Opera scrolled
![Opera scrolled](http://i.imgur.com/6f5vs6S.png)

Edge not scrolled
![Edgenot scrolled](http://i.imgur.com/TluoCxB.png)

Edge scrolled
![Edge scrolled](http://i.imgur.com/VICo93A.png)

Firefox not scrolled
![Firefox not scrolled](http://i.imgur.com/uoAXeLp.png)

Firefox scrolled
![Firefox scrolled](http://i.imgur.com/NIxtFaL.png)
