### ISSUE TITLE
Event.initEvent() has been removed from the Web standards

### ISSUE THREAD

**Issue by JinxiuLee** [jackmoore/autosize#280]
https://developer.mozilla.org/en-US/docs/Web/API/Event/initEvent

**Comment by JinxiuLee** [comment]
This feature has been removed from the Web standards. Though some browsers may still support it, it is in the process of being dropped. Do not use it in old or new projects. Pages or Web apps using it may break at any time.

**Comment by jackmoore** [comment]
Thanks for the info.  There is no equivalent in IE, so at a minimum initEvent will continue to be used.  I may add feature testing to avoid it in better browsers, but I have little concern about browsers removing support for the old way of creating custom events.

**Comment by JinxiuLee** [comment]
Thanks for your quick reply.
