### ISSUE TITLE
How can I import this project in my html?

### ISSUE THREAD

**Issue by LeeKyungMoon** [jackmoore/autosize#281]
Very happy to meet what I really want to find, but actually I have no idea how to import this project into my angular project.
I did 'npm install autosize' and checked 'autosize' package is in 'node_modules' folder in my project.

But actually, I am not sure how to import this! Is there anyone being able to help me?
and where should I put the code of 'Usage'? in the script tag?
// from a NodeList
autosize(document.querySelectorAll('textarea'));

// from a single Node
autosize(document.querySelector('textarea'));

// from a jQuery collection
autosize($('textarea'));

**Comment by jackmoore** [comment]
Look at the example file:
https://github.com/jackmoore/autosize/blob/master/example/index.html
