### ISSUE TITLE
Add back option to not create extra line

### ISSUE THREAD

**Issue by danny-wu** [jackmoore/autosize#282]
Autosize v3 seems to always add an extra line to textareas. In v1, this was set with the `append` option which could be overriden. This doesn't seem to be possible in v3.

It would be good to allow overriding this behaviour and prevent creating extra newlines.

**Comment by jackmoore** [comment]
Sorry, I don't know what you are talking about (version 1 could append newlines, current versions do not).  Are you talking about how 2 is the default number of rows?  You can change that by setting the rows attribute on your textarea element to 1.

**Comment by danny-wu** [comment]
Thanks, actually I think I misdescribed the issue (sorry). Please see https://github.com/jackmoore/autosize/issues/283
