### ISSUE TITLE
Default textarea height too big

### ISSUE THREAD

**Issue by lombas** [jackmoore/autosize#287]
When using this lib, the Textarea  default height is set to 44px, in the element style (inline), which is too big for me, I wanted it to look like an input field, with only 1 row and about 20px.

The row atribute, and the CSS height gets ignored because the height is set in the element style.

It would be nice to have a option to set the default height.

Thanks

**Comment by jackmoore** [comment]
> When using this lib, the Textarea default height is set to 44px

Are you sure this has something to do with Autosize, and isn't the normal height of the textarea?

**Comment by jackmoore** [comment]
You say you want it to be 1 row, but did you set the rows attribute on the textarea element to have that value?

**Comment by lombas** [comment]
You are right. Setting the rows attribute did it. I must have made a mistake and thought it was getting ignored. 
Thank you jack, for the quick reply.
