### ISSUE TITLE
How do you resize the element when it's loaded?

### ISSUE THREAD

**Issue by benjamin21st** [jackmoore/autosize#289]
From what I'm seeing, it seems that autosize only resizes the text area if you type in it. But what if I have a large chunk of text, and I want the textarea to be already resized before I click into it?

**Comment by jackmoore** [comment]
Use the `autosize.update` method or trigger the `autosize:update` event.

Examples in the doc:
http://www.jacklmoore.com/autosize

**Comment by benjamin21st** [comment]
It turns out the reason why both didn't work in my case was because I had my textareas `display: none`. I toggled them to block and then applied autosize and it worked perfectly. 

Maybe you should mention that in your doc just in case other people would make the same mistake as me. 

Thanks!

**Comment by jackmoore** [comment]
It's an FAQ question: http://www.jacklmoore.com/autosize/#faq-hidden

:)
