### ISSUE TITLE
Firefox isue: style is null 

### ISSUE THREAD

**Issue by cmscott2** [jackmoore/autosize#305]
In autosize.js:67:4 an error occurs because style is null.  This occurs in the init function, under the assign(ta) function, where style is initialized to window.getComputedStyle(ta, null).

After throwing a try catch around autosize($'textarea')) it works, and just logs that the style is null to the console.

**Comment by jackmoore** [comment]
What this inside an iframe?  Found an open ticket about that on the mozilla tracker: https://bugzilla.mozilla.org/show_bug.cgi?id=548397

**Comment by pppdns** [comment]
possibly related to https://github.com/jackmoore/autosize/issues/329
