### ISSUE TITLE
Textarea not resized when content changes from external events

### ISSUE THREAD

**Issue by andreszs** [jackmoore/autosize#309]
Whenever I alter the textarea contents with jQuery, there is no way to have the plugin resize the textarea. Not even when calling the `autosize()` method or triggering events such as `$('textarea').keyup();` 

Is there any way to have the plugin resize the textarea _manually_ when it doesn't notice the content has changed? Thanks.

**Comment by bcackerman** [comment]
Did you figure this out @andreszs

**Comment by jackmoore** [comment]
@bcackerman use the autosize.update method: http://www.jacklmoore.com/autosize/
