### ISSUE TITLE
Textarea at least 48px high?

### ISSUE THREAD

**Issue by Baedda** [jackmoore/autosize#311]
In my case I wanted to use this plugin to enlarge a textarea that is styled equal to a regular input type text. This is why I have set the textarea to only have a height of 30px (no border, no padding).

After I init the plugin it instantly increases the height of the textarea to 48px. I suspect this is because of line 100 where `scrollHeight` is used to determine the endHeight.

```javascript
let endHeight = ta.scrollHeight+heightOffset;
```

Maybe `scrollHeight` returns a bigger value then `ta.style.height` because it reserves some space for a possible scrollbar? I couldn´t figure out what exactly happens or if there is anything on my side I can do.

It would be nice to make autosize work for single line styled textareas, too :)

**Comment by jackmoore** [comment]
Short answer is you need to set the rows attribute to 1 on your textarea.

**Comment by Baedda** [comment]
Oh now i feally really awkward. Thank you very much for your help.
