### ISSUE TITLE
IE 11 max-height issue with display:table-cell

### ISSUE THREAD

**Issue by vagdwd** [jackmoore/autosize#316]
In my case textarea is in div and div is display: table-cell. If i set max-height for textarea, each input after the maxheight is reached creates a flickering effect in IE 11. I just faced the issue, so don't have a demo, will add soon.

**Comment by jackmoore** [comment]
Willing to reopen if anyone else experiences this or can provide a demo.  It's unlikely, but this may have been resolved in a release published since this ticket was opened.
