### ISSUE TITLE
autosize.destroy() results in NS_ERROR_UNEXPECTED under Firefox for disabled textarea

### ISSUE THREAD

**Issue by iafan** [jackmoore/autosize#317]
When calling `autosize.destroy()` on a detached and disabled textarea, we're hitting this bug in Firefox under Windows: https://bugzilla.mozilla.org/show_bug.cgi?id=889376

What happens underneath is that when ` autosize.destroy()` is called, autosize tries to run the cleanup code _by dispatching an event_, and if our disabled textarea is detached (because we're unmounting our React component that wraps an autosized textarea), Firefox throws the NS_ERROR_UNEXPECTED error.

There are currently multiple potential workarounds:

1. Wrap the call to autosize.destroy() with `try..catch` and filter out NS_ERROR_UNEXPECTED (but this may resolve in things not being cleaned up properly). This is what we currently do as a quick hack. 
2. Instead of disabling a teaxtarea, just style it as if it was disabled and use `pointer-events: none` to prevent any interaction on it. This one wasn't tested by us, but has a good chance to work.

However, I believe the best option would be to have this fixed on autosize library side. For example, by calling the cleanup code directly and not by dispatching an event.

**Comment by jackmoore** [comment]
Thanks, this is good feedback.
