### ISSUE TITLE
autosize:resized at initial display.

### ISSUE THREAD

**Issue by poliaca** [jackmoore/autosize#321]
Please also generate the autosize: resized event at initial display.
Current situation does not occur unless keyboard input is done.

**Comment by franrocio** [comment]
I need the same solution
When loading php textarea autosize

**Comment by franrocio** [comment]
lineas=$('#obs').val();
//alert (lineas);
var lines = lineas.split('\n');
var nlineas=(lines2.length)+(lines.length)+1;
var alto=nlineas * incremento;
$('#obs').css('height', alto);

**Comment by jackmoore** [comment]
Sorry for the late reply @poliaca .  This is already the way things work.  My guess is that you do not have your event handler ready at the time that the event fires.  Be sure to assign the `autosize:resized` event before assigning autosize so that you can catch the even when it fires. 

Example:

```
var ta = document.querySelector('textarea');
ta.addEventListener('autosize:resized', function(){
  console.log('textarea height updated');
});
autosize(ta);
```

**Comment by franrocio** [comment]
it does not work
 .....
.php
</div>
    <script src="js/jquery.js"></script>
    <script src="js/FqueryFra.js"></script>    
    <script src='js/autosize.js'></script>
	<script>
		autosize($('textarea'));
                var ta = document.querySelector('textarea');
                ta.addEventListener('autosize:resized', function(){
                    console.log('textarea height updated');
                 });
               autosize(ta);
	</script> 
    <script src="js/bootstrap.min.js"></script>      
  </body>

but
however in
js/FqueryFra.js
it´s ok

.js
.....


var incremento=25;
$('textarea').each(function() {	
	var ta = $(this);
	lineas=$(this).val();		
	lines = lineas.split('\n');	
	lines2 = lineas.split('\r');	
	nlineas=(lines2.length)+(lines.length)+1;
	alto=nlineas * incremento;	
	$(this).css('height', alto);	
});

**Comment by jackmoore** [comment]
@franrocio You are assigning autosize twice.  The first time the textarea is resized (from `autosize($('textarea'))`) the event fires but you aren't listening for it yet.  The 2nd time autosize is assigned to the same textarea, the textarea already has the correct size so no resize event is fired.

I don't know what your incromento script has to do with anything, that seems completely unrelated to Autosize.

**Comment by franrocio** [comment]
I can not get autosize when loading php
In php I read the database and created the lines 

<tr style='font-size:14px;' id='linLin_3' class='trLin' ><td id='iddes_3'><textarea class='form-control ttrrTextAreaLinea' rows='3'  id='descripcion_3' placeholder='descripcion'> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum pretiu</textarea>

Then if it works it will self-adjust when I write in the textarea
