### ISSUE TITLE
Can you please add to CDNJS

### ISSUE THREAD

**Issue by eldan88** [jackmoore/autosize#326]
Hi, 

 You have an awesome script. But as a developer that has all their js scripts pulled from cdnjs, logistically its annoying to have to use bower to upgrade the script in the future. Its better to have everything loaded from CDNJS. 

Can you please upload it?

**Comment by jackmoore** [comment]
Sorry, I don't personally use CDNJS but Autosize appears to already be listed with them (and up to date): https://cdnjs.com/libraries/autosize.js

**Comment by Mithgol** [comment]
@eldan88 Consider pulling npm-published scripts from https://unpkg.com/ CDN.

For maximum security,

* pull the specific version,

* [generate a hash](https://www.srihash.org/) and use it to verify integrity of the script.
