### ISSUE TITLE
Error when minified 

### ISSUE THREAD

**Issue by leMaur** [jackmoore/autosize#329]
I got this error when I minify the project
<img width="815" alt="screen shot 2017-02-13 at 10 19 12" src="https://cloud.githubusercontent.com/assets/2118799/22878466/33dd5d1e-f1da-11e6-99f6-40c879f3421b.png">

After debug with Chrome Dev Tools I've found the problem origin to line 135  https://github.com/jackmoore/autosize/blob/master/src/autosize.js#L135

Any idea on how to solve?

**Comment by jackmoore** [comment]
Does this happen when you use the provided minified file?  If not, what's the difference in the two files?

**Comment by leMaur** [comment]
After checking I found the problem in my webpack configuration.
Now, I have to figure out how to solve it.

Sorry for that!

**Comment by koox00** [comment]
Sorry to bump in on this,  
I am having the exact same issue, do you have any insight on this @leMaur ?

**Comment by pppdns** [comment]
me too, did you find out anything @leMaur and @koox00 ? `autosize.min.js` works well itself but when minimized again using `uglifyjs` it says `Uncaught TypeError: Cannot read property 'height' of undefined`. 

The original source is here:
https://github.com/jackmoore/autosize/blob/3.0.21/src/autosize.js#L135

**Comment by jackmoore** [comment]
@pppdns Thanks for posting a screen of the minified code, that either is a nasty minification error or possible misuse of one of Uglify's potentially destructive compression options.  It seems like a bug to me, I'm guessing it's limited to a specific version of Uglify.
