### ISSUE TITLE
IE9/10/11 jitter when a new row is added

### ISSUE THREAD

**Issue by gsmeets** [jackmoore/autosize#332]
I experience a jitter in IE when a new line is added to the textarea.
I've found an old unrelated issue that talked of an append option, which seems to have been a workaround for this problem.
It seems this option was dropped in v2 or v3. 

Is there some other way to work around this issue?

**Comment by jackmoore** [comment]
There probably isn't a way to fix this with current approach autosize uses.  It would probably take going back to the v1 method of keeping a mirrored textarea element, which had it's own drawbacks (maintaining a list of meaningful styles to mirror and it difficult to efficiently guarantee that both elements used the styles continuously).  Using a mirrored element is what allowed for appending a big of buffer space.

**Comment by jackmoore** [comment]
Going to close this as wontfix, as it is probably unfixable without taking a very different approach.
