### ISSUE TITLE
'autoupdate.update' method slowly

### ISSUE THREAD

**Issue by hankir** [jackmoore/autosize#333]
// The actual height not matching the style height (set via the resize method) indicates that 
// the max-height has been exceeded, in which case the overflow should be set to visible.
if (actualHeight !== styleHeight) {
    if (computed.overflowY !== 'visible') {
        changeOverflow('visible');
        resize();
        actualHeight = Math.round(parseFloat(window.getComputedStyle(ta, null).height));
    }
}

computed.overflowY !== 'visible' - Always not equals 'visible'.
When set ta.style.overflowY = 'visible' in "CSS basic box model" model computed value always will be 'auto'. It is spec of css.

1. chromium computed value is 'auto':
    https://bugs.chromium.org/p/chromium/issues/detail?id=243739
        --> https://drafts.csswg.org/css-box/#collapse-scroll
2. ie11 computed value is "scroll".

Maybe need check ta.style.overflowY !== 'visible'?

**Comment by jackmoore** [comment]
Thanks, good catch!
