### ISSUE TITLE
Is autosize.js in the src folder the autosize plugin?

### ISSUE THREAD

**Issue by knzudgt** [jackmoore/autosize#335]
I am sorry about the dumb question: is `autosize.js` inside `austosize-master/src` the autosize plugin?
I downloaded the plugin from http://www.jacklmoore.com/autosize/ and found two `autosize.js` files, one inside `austosize-master/src` and the other inside `austosize-master/dist`: which one is the correct plugin? They have different size.

I am asking this question because I need the plugin for my Ruby on Rails application and found only outdated gems. Therefore I would install the plugin as js script inside `vendor/assets/javascripts` as suggested by some documentation, and then make it available as part of the site-wide `application.js` script adding in it the line of code `//= require autosize`.

**Comment by jackmoore** [comment]
Use the files from `dist`.

**Comment by knzudgt** [comment]
One note for **Ruby on Rails** applications: in order to use autosize it is necessary to:

1. Download the jQuery `autosize` plugin from http://www.jacklmoore.com/autosize/
2. Extract the `autosize-master` folder
3. Copy the `autosize-master/dist/autosize.js` script to your application's `vendor/assets/javascripts` folder.
4. Edit the `app/assets/javascripts/application.js` file, adding the following code after the `require jquery` and `require jquery-ujs` statements:

    `//= require autosize`

Simple enough without need of dedicated gems.
