### ISSUE TITLE
Doesn't decrease size when deleting lines

### ISSUE THREAD

**Issue by pixelbreaker** [jackmoore/autosize#340]
In latest chrome this doesn't shrink the field when deleting lines of text. See gif..
I am using v4.0.0

![autosizebug](https://user-images.githubusercontent.com/219993/29973579-f7ad2c0c-8f27-11e7-8ffc-e2cf427af307.gif)

**Comment by pixelbreaker** [comment]
Same in Safari too.

**Comment by ArfanMirza** [comment]
dont shrink, if programmatically clear value!

**Comment by trollderius** [comment]
don't use css transition on the textarea

**Comment by jackmoore** [comment]
@trollderius is correct, Autosize needs to be able to change the size of the textarea immediately in order to calculate the height based on the amount of overflow.
