### ISSUE TITLE
Error: new Event is not catched

### ISSUE THREAD

**Issue by andreszs** [jackmoore/autosize#341]
The following code should be moved inside the try block to prevent errors in IE:

```javascript
var createEvent = function createEvent(name) {
    return new Event(name, { bubbles: true });
};
```
![autosize](https://user-images.githubusercontent.com/10298071/31055335-b053532c-a697-11e7-869b-2d0fbb1156af.gif)

**Comment by jackmoore** [comment]
This is the full relevant code:
```
let createEvent = (name)=> new Event(name, {bubbles: true});
try {
	new Event('test');
} catch(e) {
	// IE does not support `new Event()`
	createEvent = (name)=> {
		const evt = document.createEvent('Event');
		evt.initEvent(name, true, false);
		return evt;
	};
}
```

See that new Event is called within a try/catch to test feature support.  If there is an error, createEvent is redefined to an IE workaround.  This branching only happens once, so I don't know what you are referring to in the title about caching.

I'm not familiar with Visual Studio, but it seems to suggest that it was going to warn you regardless if the error was caught or not.  Your screenshot says "If there is a handler for this exception, the program may be safely continued", and the handler for Autosize is the `catch` statement.  Everything seems to be working as intended (exception raised -> caught -> code branched), so I don't think there is anything to worry about.
