### ISSUE TITLE
Autosize plugin in edit form dont work correct?

### ISSUE THREAD

**Issue by NogerbekNurzhan** [jackmoore/autosize#342]
Hello! First of all thanks for this project! =)

I have strange problem and think that its bug. Can you say how I can fix it?

I use bootstrap 3.3.7. I have edit form modal with two tab. Inside them I have <textarea> elements. I use autosize plugin to textarea elements.

I load data to form with ajax and inside textarea I have long text but autosize plugin dont change textarea height when I open modal. Only when user start to write plugin works.

**HTML:**
```
<!DOCTYPE html>
<html lang="en">
<head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
<div class="dashboard-wrapper">
    <div id="dashboard-content">
        <div class="modal fade">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <form method="post" action="">
                        <div class="modal-body">
                            <ul class="nav nav-tabs nav-justified">
                                <li class="active"><a class="tabnav" data-toggle="tab" href="#TabFirst">FIRST</a></li>
                                <li><a class="tabnav" data-toggle="tab" href="#TabSecond">SECOND</a></li>
                            </ul>

                            <div class="tab-content">
                                <div id="TabFisrt" class="tab-pane fade in active">
                                    <div class="form-group">
                                        <label for="first_body">First Description</label>
                                        <div class="textarea-wrapper">
                                            <textarea name="body" class="form-control" id="first_body"></textarea>
                                            <i class="fa fa-arrows textarea-icon" aria-hidden="true"></i>
                                        </div>
                                    </div>
                                </div>

                                <div id="TabSecond" class="tab-pane fade in active">
                                    <div class="form-group">
                                        <label for="second_body">Second Description</label>
                                        <div class="textarea-wrapper">
                                            <textarea name="body" class="form-control" id="second_body"></textarea>
                                            <i class="fa fa-arrows textarea-icon" aria-hidden="true"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/autosize.js/4.0.0/autosize.js"></script>
</body>
</html>
```

**JS**:
```
autosize(document.querySelectorAll('#first_body'));
autosize(document.querySelectorAll('#second_body'));
```

**Comment by jackmoore** [comment]
Autosize has no way of knowing when you use JavaScript to change the value of the textarea element, as there is no handler or event that the browser fires in order for me to be able to automatically detect that.

However, you call Autosize's update method after you've changed the textarea value and it will recalculate the size.

So if you are using ajax, it would look something like this:

```
var first_body = document.querySelector('#first_body');
autosize(first_body);
$.ajax('example.html').done(function(text){
  first_body.value = text;
  autosize. update(first_body);
});
```

**Comment by jackmoore** [comment]
Sorry, I may have misinterpreted the situation.  There should be some sort of callback or event that you can use to call `autosize.update` after you open the modal.  Autosize requires that the element be in the flow of the document in order to be able to correctly estimate a size (the textarea element has to have layout), so if that is hidden or detached from the DOM until the modal is displayed, Autosize has no way of calculating a size for that.

**Comment by NogerbekNurzhan** [comment]
I use as you said `autosize.update(document.querySelectorAll('textarea'));` but only textarea in first tab works. Textarea in the second tab dont work. Maybe cause when the page is loaded only first tab is active (first textarea is visable to user at start). The second textarea in the second tab is in DOM but its invisible when page loaded I think. How do you think is there any way to use `autosize.update` method to second textarea in second tab?

**Comment by jackmoore** [comment]
Sorry, Autosize can't work with hidden elements because they are not in the document flow / have layout.  You could either call `autosize.update` after the tab panel is displayed, or make the panel not visible to the visitor in a way that keeps layout for it's contents.  For example, switching the panels from height auto => height 0 instead of display block => display hidden.
