### ISSUE TITLE
Textarea not returning to starting height

### ISSUE THREAD

**Issue by StudioVDS** [jackmoore/autosize#348]
Hi,

I'm using your plugin with jquery, it's great! Thanks a lot. I have some difficulties getting it to work right. I have two issues.

I use this code:
`$('textarea').each(function () {
        var ta = this;
        autosize(ta);
    }).on('autosize:resized', function () {
        console.log('resized');
    });`

1. When I write something the height is expanding perfectly but when I delete the text the height doesn't get back to the starting height so it stays expanded.

2. I use the autosize:resized trigger to see if the textarea is changed in height, this works wel when typing characters. But when I use the 'return' button the height of the textarea changes but the log isn't triggered it get's triggered when I start typing characters again.

Hope you can help me out with these problems.
Thanks

**Comment by jackmoore** [comment]
Sorry, I haven't heard of anyone having issue with autosize not picking up delete or carriage return.  I would have to reproduce it myself to be of any help with that.  You should state what browser and version you are using, and what version of autosize.  If this is actually a problem with Autosize then it is probably going to be limited to a specific browser version, but my guess is that some other JavaScript on your page that is unintentionally interfering with the event.

**Comment by StudioVDS** [comment]
Thanks for your quick reply, for a little more info.
I'm using: Chrome Version 63.0.3239.84 on OSX High Sierra and version 4.0.0 of autosize.

The example file in your download is working as expected, it tried to remove all other javascript and all other libraries but this doesn't solve the problem. Any suggestion on how I can debug?

**Comment by jackmoore** [comment]
I mean if the script works fine until you put it on your page that should mean that the page is introducing a conflict. I'll look at it if you post a demo, otherwise I think you'll be on your own as it sounds specific to your page.

**Comment by StudioVDS** [comment]
Yes I understand that. There is to much going on in the site to cut out an example. I’ll dig in to it. When I found the problem I’ll post it here.

**Comment by StudioVDS** [comment]
I found the problem, no js but css is the problem. I wanted to make the textarea grow smooth so I added a `transition: height .3s;` to the textarea in my css file. Anything I can do about this apart from removing the transition?

**Comment by jackmoore** [comment]
Ah, that would do it.  Autosize changes the height quickly in order to get measurements and is incompatible with transitions.  You would either have to use a different sizing script that mirrors your text into an offscreen / invisible textarea element which is used as the basis for calculations (this is how the original version of Autosize worked, but it comes with it's own caveats), or replace your textarea with something like a contenteditable div.
