### ISSUE TITLE
Horizontal scrollbar causes text to be cut off

### ISSUE THREAD

**Issue by drssoccer55** [jackmoore/autosize#374]
I wanted a resizable text area with a horizontal scroll and no text-wrapping so I added the following css to my text area:
` 
overflow-x: auto !important;
white-space: pre;
` 

It seems like there is nothing in the library to take into account the size of the horizontal scrollbar so this results in the text being cut off. Even if the overflow-x is 'scroll' instead of 'auto' I still would run into this issue.

![image](https://user-images.githubusercontent.com/23265878/65471428-e93fb980-de23-11e9-9d80-e28fb9685f0a.png)

I guess I am breaking intended behavior with my overflow-x override but this seems like a feature that might be desired by others in the future.

**Comment by jackmoore** [comment]
Understandable, but out of scope of what Autosize was built to do
