### ISSUE TITLE
Not working on mobile chrome

### ISSUE THREAD

**Issue by radenkozec** [jackmoore/autosize#382]
Everything works normally on desktop chrome.
When I open page on mobile chrome there are few more blank lines bellow textarea. This only happens in mobile chrome.
On mobile firefox looks ok.
Is this related to this: https://stackoverflow.com/questions/34942305/unable-to-resize-the-textarea-height

Any tip? Thanks

**Comment by jackmoore** [comment]
Sorry, I'm not sure I follow the issue. I understand that there is additional blank space below the textarea, but is autosize otherwise working correct? Do you only get the additional blank space if autosize is enabled?

**Comment by radenkozec** [comment]
Thanks for fast response. I only get this bug on Google Chrome on Android.
There is a additional blank space which is large inside textarea after actual text. 
If text is bigger, bigger is blank space. 

This only happens when autosize is enabled.

**Comment by radenkozec** [comment]
PS. Also be aware this only happens on real mobile devices, in browser using chrome dev tools mobile works correctly.

**Comment by jackmoore** [comment]
@radenkozec Sorry, I was not able to recreate the issue. I don't doubt you, it's just that I couldn't recreate with a quick test. Does this empty space appear only when you first assign autosize, or does it persist after typing in the textarea? Also, if you could provide a link to a demo that would be helpful.

**Comment by radenkozec** [comment]
This is style of my textArea:
`.editableInputTextArea {
    background: 0 0;
    background-color: #f4f4f4;
    border: 0;
    border-radius: 3px;
    box-shadow: none;
    min-height: 44px;
    resize: none;
    width: 100%;
    padding: 5px 6px;
    overflow: hidden !important;
    word-wrap: break-word;
}`
Blanks space is persisted even if I type in the textarea.
If this is not helpful I can send you some demo account and links for my application where you can test it on live app.

**Comment by radenkozec** [comment]
UPDATE: It seams it is related to focus into textarea https://stackoverflow.com/questions/59889630/mobile-browser-textarea-height-change-issue-on-focus
