### ISSUE TITLE
Bug: Plugin Sporadically Adds Disabled Vertical Scrollbar

### ISSUE THREAD

**Issue by missionbaymedia** [jackmoore/autosize#394]
Bug found on Chrome and Edge - the plugin periodically adds a disabled vertical scrollbar which doesn't seem to be the intended behavior. This bug also seems to have appeared relatively recently - only in the last few months.
![image](https://user-images.githubusercontent.com/70244621/134430743-846fdc6c-6c4c-4ff4-ab33-26f805bcf86f.png)

**Comment by jackmoore** [comment]
Sorry, I never looked into this because it sounded like a temporary regression in Blink. I've not encountered it, so I'm going to assume it was resolved at the browser level. Thanks for the report.
