### ISSUE TITLE
When the end of the line is reached, pressing the spacebar does not switch to a new line.

### ISSUE THREAD

**Issue by m2sahin** [jackmoore/autosize#397]
When the end of the line is reached, pressing the spacebar does not switch to a new line. Press the space key 100 times at the end of the line, it will save it, but when you press another key it will switch to the new line and you will see the space then.

**Comment by FlashTang** [comment]
@m2sahin 
Try apply css to textarea
`white-space: break-spaces;`
or
`textArea.style.whiteSpace = "break-spaces";`
