### ISSUE TITLE
Conflicting with LastPass Browser Extension

### ISSUE THREAD

**Issue by DaveHogan** [jackmoore/autosize#402]
Not sure if it's something with my specific setup, but with Brave Browser and Lastpass plug-in / browser extension, I get a conflict.

![image](https://user-images.githubusercontent.com/227751/211125323-036e204e-4286-4e8f-9305-7b67eaae28b7.png)

I can focus and blur out of the textarea fine. It appears to only appear in the console log when I hit enter in the TextArea field.

Very similar issue with this other project: https://github.com/mui/material-ui/issues/14860
Looks like the underlying cause is LastPast itself: https://community.logmein.com/t5/LastPass-Support-Discussions/onloadwff-js-Assertion-failed-Input-argument-is-not-an-HTML/m-p/246491

Browser: Version 1.46.144  Chromium: 108.0.5359.128 (Official Build)  (64-bit)
Lastpass: 4.106.1

**Comment by jackmoore** [comment]
Yeah, sorry, none of that looks familiar to me.
