### ISSUE TITLE
[issue]autosize after changing padding

### ISSUE THREAD

**Issue by FlashTang** [jackmoore/autosize#404]
```
this.textArea!.style.paddingLeft ="50px";
this.textArea!.style.paddingTop = "50px";
this.textArea!.style.paddingRight =  "50px";
this.textArea!.style.paddingBottom = "50px";

autosize(this.textArea!); // works fine

this.textArea!.style.paddingLeft ="100px";
this.textArea!.style.paddingTop = "100px";
this.textArea!.style.paddingRight =  "100px";
this.textArea!.style.paddingBottom = "100px";

autosize.update(this.textArea!); // wrong height .100px more than correct

the solution  for now I found is set padding to 50px (original padding after autosize init)
then autosize.update(this.textArea!); // correct
then  set padding back to 100px
```

is there a way to fix this without switching padding ?

like : autosize.autoSwitchPaddings = true; // so this will not break the original behave (unless set this line)

Thank you

**Comment by jackmoore** [comment]
@FlashTang I was not able to reproduce the issue, but I think I know what the underlying problem was. Try the latest version (v6.0.0) and see if that resolves things for you.

**Comment by FlashTang** [comment]
@jackmoore 
Great ! problem solved by updating to the latest version , since I was using the version I downloaded last year.
thanks again.
