### ISSUE TITLE
Release note for each major update?

### ISSUE THREAD

**Issue by himself65** [jackmoore/autosize#405]
I saw 6.0.x these days, but I don't know what the difference with the previous version is. So I'm afraid breaking changes when I upgrade it

**Comment by jackmoore** [comment]
Sorry, I need to start doing that so I'll leave this ticket open. In the meantime, changes are listed in the changelog: https://github.com/jackmoore/autosize/blob/master/changelog.md

**Comment by jackmoore** [comment]
Decided I'm not going to go back and make release for all old tags, but I did create releases for 6.0.0 and 6.0.1. The API did not change with 6.0.0 so it should require no code changes on your part, but I did drop support for Internet Explorer and some of the internal mechanics were tweaked which could have introduced bugs.
