### ISSUE TITLE
Text "jumps" when new line since 6.0.1

### ISSUE THREAD

**Issue by coudrak** [jackmoore/autosize#406]
Since the version 6.0.1 (no problem with 6.0.0) the previous lines "jump" for a short while, when you press Enter or just write a long line and the textarea expands with a new line.
It's very short (some milliseconds) but the effect is visually not nice...
Difficult to explain, so I made a video: https://drive.google.com/file/d/1xk6jHRhBbnzR6E9qBbNDAlQldYW-l574/view

Chrome or Firefox, under Windows.

**Comment by jackmoore** [comment]
@coudrak Thanks for the video. Are you sure no CSS transition or animation is being inherited by that textarea element? Those aren't compatible with the way autosize functions.

**Comment by coudrak** [comment]
Aaah yes, indeed, sorry!
I found an old `textarea { -webkit-transition: height 0.2s; -moz-transition: height 0.2s; transition: height 0.2s; }` in my css.
I removed it and now it works perfectly again.
Thanks a lot!

**Comment by coudrak** [comment]
I close the issue.
